# Create mados user and group for live environment
u mados 1000:1000 "madOS User" /home/mados /usr/bin/zsh
u alpm - "ALPM system user" /var/lib/pacman /usr/bin/nologin
m mados wheel
m mados video
m mados audio
m mados input
m mados seat
