sonar.projectKey=madkoding_mad-os
sonar.projectName=madOS
sonar.sources=airootfs,.github
sonar.python.version=3.12
sonar.tests=tests
sonar.test.inclusions=**/*.py
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.png,**/*.jpg,**/*.ico,**/*.svg,**/node_modules/**,**/translations.py
