title    madOS Live (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-mados
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-mados.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=256M quiet splash intel_idle.max_cstate=1 i915.enable_dc=0 ahci.mobile_lpm_policy=1
