title    madOS Live (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% archisolabel=%ARCHISO_LABEL% cow_spacesize=256M quiet splash loglevel=3 rd.udev.log_level=3 udev.log_priority=3 rd.systemd.show_status=false systemd.show_status=false vt.global_cursor_default=0 plymouth.ignore-serial-consoles intel_idle.max_cstate=1 i915.enable_dc=0 ahci.mobile_lpm_policy=1
