title    madOS Live (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-mados
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-mados.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=256M quiet splash console=ttyS0,115200 earlyprintk=serial loglevel=7
