title    madOS Live (Safe Graphics) (%ARCH%, UEFI)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-mados
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-mados.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=256M nomodeset root=/dev/sr0 console=ttyS0,115200 earlyprintk=serial loglevel=7 floppy=0
