title    madOS Live (Safe Compat) (%ARCH%, UEFI)
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-mados
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-mados.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=256M nomodeset i915.enable_psr=0 pcie_aspm=off nvme_core.default_ps_max_latency_us=0 quiet splash
