# Load zram module early for compressed swap
zram

# Load iptables modules early for UFW firewall
ip_tables
ip6_tables
iptable_nat
iptable_filter
ip6table_filter
nf_conntrack_ftp
nf_nat_ftp
nf_conntrack_netbios_ns
