general {
    col.active_border = rgba(00ffffee) rgba(ff00ffee) 45deg
    col.inactive_border = rgba(595959aa)
}

decoration {
    shadow {
        color = rgba(00000088)
        color_inactive = rgba(00000055)
    }
}

group {
    col.border_active = rgba(00ffffee) rgba(ff00ffee) 45deg
    col.border_inactive = rgba(595959aa)
    col.border_locked_active = rgba(00ffddee) rgba(00ffffee) 45deg
    col.border_locked_inactive = rgba(5f5f5f88)

    groupbar {
        col.active = rgba(00ffffcc)
        col.inactive = rgba(30303acc)
        text_color = rgba(ffffffff)
    }
}
